apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer # Change to NodePort if LoadBalancer is unavailable
